---
- name: Deploy FTP Server
  hosts: master
  become: true

  vars_prompt:
    - name: usrname
      prompt: "Enter the username for ftp server"
      private: false

    - name: user_password
      prompt: "Enter the password for the user"
      private: yes

  tasks:
    - name: Install vsftpd package
      apt:
        name: vsftpd
        state: present
      become: true

    - name: Enable UFW
      ufw:
        state: enabled

    - name: UFW open ports for ssh
      ufw:
        rule: allow
        port: "22"
        proto: tcp

    - name: UFW open ports 20, 21, 22 and 900 for TCP
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      with_items:
        - 20
        - 21
        - 900

    - name: UFW open ports 20, 21, 22 and 900 for UDP
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: udp
      with_items:
        - 20
        - 21
        - 900

    - name: Allow TCP ports 40000-50000
      ufw:
        rule: allow
        port: "40000:50000"
        proto: tcp

    - name: Configure vsftpd
      copy:
        src: ./vsftpd.conf
        dest: /etc/vsftpd.conf

    - name: Add user "{{ usrname }}"
      user:
        name: "{{ usrname }}"
        state: present
        shell: /bin/bash

    - name: Set password for "{{ usrname }}"
      user:
        name: "{{ usrname }}"
        password: "{{ user_password | password_hash('sha512') }}"
        update_password: always

    - name: Create FTP directory without write permission
      file:
        path: /home/{{ usrname }}/ftp
        state: directory
        owner: nobody
        group: nogroup
        mode: '0755'

    - name: Create FTP files directory
      file:
        path: /home/{{ usrname }}/ftp/files
        state: directory
        owner: "{{ usrname }}"
        group: "{{ usrname }}"
        mode: '0755'

    - name: Append user to vsftpd.userlist
      lineinfile:
        path: /etc/vsftpd.userlist
        line: "{{ usrname }}"
        create: yes

    - name: Restart FTP service
      service:
        name: vsftpd
        state: restarted
        
    


